### ISSUE TITLE
Mixed content error causes make page to not load

### ISSUE THREAD

**Issue by simonwex** [mozilla/webmaker-firehose#15]
![image](https://cloud.githubusercontent.com/assets/25260/6153103/fe699f48-b1d6-11e4-804b-a0b1a8a9319d.png)

Error in Chrome:
![image](https://cloud.githubusercontent.com/assets/25260/6153114/1abc8020-b1d7-11e4-99e5-22eb1a1829ba.png)

Error in Firefox:
![image](https://cloud.githubusercontent.com/assets/25260/6153155/785bb246-b1d7-11e4-99b0-f11dbea55c82.png)

**Comment by cadecairos** [comment]
I build a proxy route for make urls that use https, but the pages use relative urls, which break for obvious reasons... mixed content sucks!

https://github.com/cadecairos/webmaker-firehose/tree/mixed-content-proxy

**Comment by simonwex** [comment]
Relative URLs? Or absolute paths? I'm not sure those would work anyway. Bobby's make is a bit strange. Can we point this at production data?

**Comment by cadecairos** [comment]
fixed by #18
