### ISSUE TITLE
Community MGMT Improvements for Webmaker App Beta

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-firehose#25]
#### Foundations
- Broken on node 12 (bad dependencies). Find out if node 10 has LTS for security and other fixes. Otherwise, need to create an upgrade plan.
- Should connect via OAuth to api.webmaker.org to interact with user/project data
#### Firehose UI
- Implement gallery view
#### Tagging
- Add tags to projects
- Search for projects by tag
- List projects by tag (in a gallery, preferably) to give out to public
#### Projects
- Only uses soft-delete right now (from MakeAPI)
  - Need to be able to actually delete projects
#### Users
- Editing user privilege level would be very useful as community grows
  - Otherwise need clear documentation about user privilege levels that I can manipulate in DB directly
- Banning users
- Suspending users
- Send email to user to warn them about conduct
- Stats (# of projects, # of warnings, # of features, privilege level, etc.)
  - Admin only -- could just be a text readout

**Comment by thisandagain** [comment]
Excellent. Thanks for the overview / evaluation @secretrobotron
