### ISSUE TITLE
When deleting a make, we should have undo

### ISSUE THREAD

**Issue by simonwex** [mozilla/webmaker-firehose#6]
Deleting is very easy. We should show a message when we delete a make and offer an option to "undo delete".

I'd even say this is critical with having the delete key `d` next to the feature key `f`.

**Comment by cadecairos** [comment]
I'm not even sure if the API supports undoing a delete. might need an enhancement there.

**Comment by cadecairos** [comment]
@simonwex  Would a confirmation dialog be enough?

**Comment by thisandagain** [comment]
:+1: on just having a confirmation dialog for now.
